[package]
name = "mean-images"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.7", features = ["rgb"] }
rayon = "1.7.0"
walkdir = "2.3.3"
